version: '3.7'

services:
  pcs-mqwebproxy-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - EventBusType=${PCS_EVENT_BUS_TYPE:-RabbitMQ}
      - EventBusConnection=${PCS_EVENT_BUS:-rabbitmq}
      - EventBusUsername=${PCS_EVENT_BUS_USERNAME:-guest}
      - EventBusPassword=${PCS_EVENT_BUS_PASSWORD:-guest}
      - PATH_BASE=/pcs-mqwebproxy-api
    ports:
      - "80"
