version: '3.7'

services:
  pcs-mqwebproxy-api:
    image: ${DOCKER_REGISTRY:-parusnik}/pcs/mqwebproxy-api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/Pcs.MqWebProxy.Api/Dockerfile
